version: "3"
services:
  webserver:
    build: ./webserver
    volumes:
      - ./webserver/src:/var/www/html
    networks:
      - default
  api:
    build: ./api
    networks:
      - default
    depends_on:
      - db

  nginx-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
    depends_on:
      - api
      - webserver
      - db
  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bolsa
      MYSQL_ROOT_PASSWORD:
        # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        # entrypoint: [""]
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: [ db ]
    ports: [ 8080:80 ]
